name: ci-dev

on: push

jobs:
  test-dev-versions:
    continue-on-error: true
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.12"]
        link: ["https://gitlab.com/ase/ase.git", "https://github.com/ACEsuit/mace.git"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --extra all

    - name: Install dev versions
      run: |
        uv pip install ${{ matrix.link }} -U

    - name: Run test suite
      env:
        # show timings of tests
        PYTEST_ADDOPTS: "--durations=0"
      run: uv run --no-sync pytest .
